### ISSUE TITLE
$HOME/.cache/go-build caching

### ISSUE THREAD

**Issue by ahmetb** [mvdan/github-actions-golang#7]
The readme says for `How do I set up caching between builds?` the path can be `~/go/pkg/mod`.
However it seems that's only for source files to be cached.

If you are like me and you do cross-compilation of binaries to 10+ architectures, you probably need to cache `~/.cache/go-build/` directory as well. Otherwise you're waiting for all Go stdlibs (and deps cached in `~/go/pkg/mod`) to recompile ––which is the majority of the time spent.

Thoughts?

**Comment by mvdan** [comment]
This is a good question. It depends :) I think the answer boils down to two tradeoffs: reliability and speed.

First, reliability. Downloading a file is generally far less reliable than compiling a piece of code locally (without any network activity). Even in the face of proxy.golang.org which is available nearly all the time, there are plenty of scenarios where a module download can fail. Maybe the network is flaky and the connection fails. Maybe you're fetching private code that isn't in any GOPROXY, and the VCS host is down.

On the other hand, a local build can only flake if something is terribly wrong with the machine. In that scenario, there's not much you can do, and caching wouldn't save you.

The other aspect is speed.

If you have a very fast internet connection, it could be just as fast to download all dependencies from GOPROXY instead of loading them from the cache, because the cache here is generally fetched from the internal network.

If you have a very powerful CPU, it could be faster to rebuild multiple Go packages than to fetch the build cache from the cache server. This can be especially true if you only compile pure Go libraries, since most Go build bottlenecks are either cgo or linking large binaries.

In general, I've found that Go builds very fast, to the point that caching builds in CI is often not a big win. This will depend on what your CI machine looks like, though, and how the cache is stored and obtained. I haven't done that kind of testing/benchmarking with GitHub Actions :)

--

To answer your question more directly - I'm not sure. I think only caching the module downloads is probably the right tradeoff for most projects. Another factor with Actions is that a repository has a limited amount of cache storage; if you cache too many things, the caches might start expiring too soon. Maybe we could add a follow-up suggestion that, if the builds are too slow and there is enough space in your cache, one can try also caching Go builds.

**Comment by ahmetb** [comment]
Yeah I get your points now, I think most people using this are using it on GitHub, possibly on free tier, so I assume the CPU on the shared machine is probably more scarce than the network resources (after all, most of the packages are pulled from GitHub, and the CI runs on GitHub as well).

That said, having more reliable package downloads is also important.

Maybe we can consider having two different cache options, one for source files, and one for build results. To give an example on how this impacts me, take a look at https://github.com/ahmetb/kubectx/runs/823981433?check_suite_focus=true (with "Show timestamps" on).

This build has taken 4m29s, where 6s was spend on `go mod download` and 4m16s was spent on building binaries for the 12 different os/arch pairs. I suspect this is happening because it keeps re-building the stdlib and all packages for all os/arch pairs every time.

**Comment by mvdan** [comment]
Could you compare those times with and without caching, for both `go mod download` and `go build`? It would be interesting what relative speed-up you get on either.

From https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy:

> GitHub will remove any cache entries that have not been accessed in over 7 days. There is no limit on the number of caches you can store, but the total size of all caches in a repository is limited to 5 GB. If you exceed this limit, GitHub will save your cache but will begin evicting caches until the total size is less than 5 GB.

It seems like they've increased the limits, and they also added zstd compression in actions/cache@v2, so the whole thing should be far more powerful now. When I first wrote this guide, I seem to recall that the cache limit was much smaller, in the order of hundreds of megabytes.

I've looked at the GOCACHE on my daily development machine and it's sitting at 1.3GiB, so I think most CI build caches should be well under half a gigabyte (unless one does tons of cross-compilation).

**Comment by mvdan** [comment]
I'm still happy to add an extra example on how to cache both the download and build caches, by the way. This discussion is more about whether we should offer both options separately, or strongly recommend caching both by default. I default to the former, because the build cache could get quite large depending on the project.

**Comment by mvdan** [comment]
I've gone ahead and added an example. The first example is still just about the module download cache, because I still think that's probably what most people should start with.

If you have any more thoughts, please feel free to leave a comment, open a new issue, or raise a PR.
